name: GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Gradle
          uses: gradle/gradle-build-action@v2
          with:
            arguments: build
